USE WMS
GO

CREATE OR ALTER PROCEDURE sp_thr
    @warehouseId varchar(10),
    @itemCode varchar(255) = NULL,
	@openingStockDateFrom DATETIME,
    @openingStockDateTo DATETIME,
	@closingStockDateFrom DATETIME,
    @closingStockDateTo DATETIME
AS
BEGIN
    -- Validate the input parameters
    IF @warehouseId IS NULL OR @warehouseId = ''
    BEGIN
        RAISERROR('Invalid warehouse id', 16, 1)
        RETURN
    END
	
	IF @openingStockDateFrom IS NULL OR @openingStockDateTo IS NULL
    BEGIN
        RAISERROR('Invalid date range', 16, 1)
        RETURN
    END
	
	IF @closingStockDateFrom IS NULL OR @closingStockDateTo IS NULL
    BEGIN
        RAISERROR('Invalid date range', 16, 1)
        RETURN
    END
    -- Set itemCode as Null when itemCode = 0 since Spring boot to stored procedure unable to send null value input
    IF @itemCode = '0'
	BEGIN
	SET @itemCode = NULL
	END
	
	-- Create Temporary Table tbltransactionhistoryresults
	CREATE TABLE #THR
	(C_ID NVARCHAR(10),
	PLANT_ID NVARCHAR(10),
	LANG_ID NVARCHAR(10),
	WH_ID NVARCHAR(10),
	ITM_CODE NVARCHAR(100),
	TEXT NVARCHAR(255),
	IS_OS_QTY FLOAT DEFAULT 0,
	PA_OS_QTY FLOAT DEFAULT 0,
	PI_OS_QTY FLOAT DEFAULT 0,
	IV_OS_QTY FLOAT DEFAULT 0,
	PA_CS_QTY FLOAT DEFAULT 0,
	PI_CS_QTY FLOAT DEFAULT 0,
	IV_CS_QTY FLOAT DEFAULT 0,
	IV_QTY FLOAT DEFAULT 0,
	PRIMARY KEY (C_ID,PLANT_ID,LANG_ID,WH_ID,ITM_CODE));
	
	-- itemCode and Description from imbasicData1 to temp table 
	INSERT INTO #THR(C_ID,PLANT_ID,WH_ID,LANG_ID,ITM_CODE,TEXT) 
	SELECT C_ID,PLANT_ID,WH_ID,LANG_ID,ITM_CODE,TEXT FROM TBLIMBASICDATA1 
	WHERE C_ID='1000' AND PLANT_ID='1001' AND LANG_ID='EN' AND IS_DELETED=0 
	AND WH_ID=@warehouseId
	AND itm_code = ISNULL(@itemCode,itm_code)
	
	-- update the temp table with inventory qty and allocated qty from inventorystock table
	SELECT C_ID,PLANT_ID,LANG_ID,WH_ID,ITM_CODE,INV_QTY,ALLOC_QTY,BIN_CL_ID 
	INTO #IVS FROM TBLINVENTORYSTOCK 
	WHERE C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND IS_DELETED=0 
	AND BIN_CL_ID IN (1,4) 
	AND WH_ID=@warehouseId
	
	-- update the temp table with inventory qty and allocated qty from inventory table
	SELECT C_ID,PLANT_ID,LANG_ID,WH_ID,ITM_CODE,INV_QTY,ALLOC_QTY,BIN_CL_ID 
	INTO #IV FROM TBLINVENTORY 
	WHERE C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND IS_DELETED=0 
	AND BIN_CL_ID IN (1) 
	AND WH_ID=@warehouseId
	
	-- putaway line table to temp table pal
	SELECT C_ID,PLANT_ID,LANG_ID,WH_ID,ITM_CODE,PA_CNF_QTY,PA_CTD_ON,STATUS_ID 
	INTO #PAL FROM TBLPUTAWAYLINE 
	WHERE C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND IS_DELETED=0 
	AND STATUS_ID IN (20) 
	AND WH_ID=@warehouseId 
	AND PA_CTD_ON BETWEEN @openingStockDateFrom AND @closingStockDateTo
	
	-- pickup line table to temp table pul
	SELECT C_ID,PLANT_ID,LANG_ID,WH_ID,ITM_CODE,PICK_CNF_QTY,PICK_CTD_ON,STATUS_ID 
	INTO #PUL FROM TBLPICKUPLINE 
	WHERE C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND IS_DELETED=0 
	AND STATUS_ID IN (50,59) 
	AND WH_ID=@warehouseId 
	AND PICK_CTD_ON BETWEEN @openingStockDateFrom AND @closingStockDateTo

	-- inv movement table to temp table ivm
	SELECT C_ID,PLANT_ID,LANG_ID,WH_ID,ITM_CODE,MVT_QTY,IM_CTD_ON,MVT_TYP_ID,SUB_MVT_TYP_ID 
	INTO #IVM FROM TBLINVENTORYMOVEMENT 
	WHERE C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND IS_DELETED=0 
	AND MVT_TYP_ID = 4 AND SUB_MVT_TYP_ID = 1 
	AND WH_ID=@warehouseId AND IM_CTD_ON BETWEEN @openingStockDateFrom AND @closingStockDateTo
	
	-- select itemcode from inventory, putaway, pickup, inv movement and union the result and store in temp table itc
	--SELECT ITM_CODE INTO #ITC FROM
	--(SELECT ITM_CODE FROM #IVS WHERE C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND WH_ID=@warehouseId
	--UNION
	--SELECT ITM_CODE FROM #PAL WHERE C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND WH_ID=@warehouseId
	--UNION 
	--SELECT ITM_CODE FROM #PUL WHERE C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND WH_ID=@warehouseId
	--UNION 
	--SELECT ITM_CODE FROM #IVM WHERE C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND WH_ID=@warehouseId) Y
	
	-- IVS Temp Table to THR
	UPDATE TH SET TH.IS_OS_QTY = X.VALUE FROM #THR TH INNER JOIN
	(SELECT (SUM(COALESCE(INV_QTY,0)) + SUM(COALESCE(ALLOC_QTY,0))) VALUE, ITM_CODE, C_ID, PLANT_ID, WH_ID, LANG_ID FROM #IVS
	WHERE 
	--ITM_CODE IN (SELECT ITM_CODE FROM #ITC) AND 
	C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND 
	BIN_CL_ID IN (1,4) AND 
	WH_ID=@warehouseId 
	GROUP BY ITM_CODE,C_ID,PLANT_ID,LANG_ID,WH_ID,LANG_ID) X ON 
	X.C_ID = TH.C_ID AND X.PLANT_ID = TH.PLANT_ID AND X.LANG_ID = TH.LANG_ID AND X.ITM_CODE=TH.ITM_CODE
	
	-- IV Temp Table to THR
	UPDATE TH SET TH.IV_QTY = X.VALUE FROM #THR TH INNER JOIN
	(SELECT (SUM(COALESCE(INV_QTY,0)) + SUM(COALESCE(ALLOC_QTY,0))) VALUE, ITM_CODE, C_ID, PLANT_ID, WH_ID, LANG_ID FROM #IV
	WHERE 
	--ITM_CODE IN (SELECT ITM_CODE FROM #ITC) AND 
	C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND 
	BIN_CL_ID IN (1) AND 
	WH_ID=@warehouseId 
	GROUP BY ITM_CODE,C_ID,PLANT_ID,LANG_ID,WH_ID,LANG_ID) X ON 
	X.C_ID = TH.C_ID AND X.PLANT_ID = TH.PLANT_ID AND X.LANG_ID = TH.LANG_ID AND X.ITM_CODE=TH.ITM_CODE
	
	-- PAL Temp Table to THR
	UPDATE TH SET TH.PA_OS_QTY = X.VALUE FROM #THR TH INNER JOIN
	(SELECT SUM(PA_CNF_QTY) VALUE,ITM_CODE, C_ID, PLANT_ID, WH_ID, LANG_ID FROM #PAL 
	WHERE 
	--ITM_CODE IN (SELECT ITM_CODE FROM #ITC) AND 
	C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND 
	STATUS_ID IN (20) AND 
	WH_ID=@warehouseId 
	AND PA_CTD_ON BETWEEN @openingStockDateFrom AND @openingStockDateTo 
	GROUP BY ITM_CODE,C_ID,PLANT_ID,LANG_ID,WH_ID,LANG_ID) X ON 
	X.C_ID = TH.C_ID AND X.PLANT_ID = TH.PLANT_ID AND X.LANG_ID = TH.LANG_ID AND X.ITM_CODE=TH.ITM_CODE

	-- PUL Temp Table to THR
	UPDATE TH SET TH.PI_OS_QTY = X.VALUE FROM #THR TH INNER JOIN
	(SELECT SUM(PICK_CNF_QTY) VALUE,ITM_CODE, C_ID, PLANT_ID, WH_ID, LANG_ID FROM #PUL 
	WHERE 
	--ITM_CODE IN (SELECT ITM_CODE FROM #ITC) AND 
	C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND 
	STATUS_ID IN (50,59) AND
	WH_ID=@warehouseId 
	AND PICK_CTD_ON BETWEEN @openingStockDateFrom AND @openingStockDateTo 
	GROUP BY ITM_CODE,C_ID,PLANT_ID,LANG_ID,WH_ID,LANG_ID) X ON 
	X.C_ID = TH.C_ID AND X.PLANT_ID = TH.PLANT_ID AND X.LANG_ID = TH.LANG_ID AND X.ITM_CODE=TH.ITM_CODE

	-- IVM Temp Table to THR
	UPDATE TH SET TH.IV_OS_QTY = X.VALUE FROM #THR TH INNER JOIN
	(SELECT SUM(MVT_QTY) VALUE,ITM_CODE, C_ID, PLANT_ID, WH_ID, LANG_ID FROM #IVM 
	WHERE 
	--ITM_CODE IN (SELECT ITM_CODE FROM #ITC) AND 
	C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND 
	MVT_TYP_ID = 4 AND SUB_MVT_TYP_ID = 1 AND
	WH_ID=@warehouseId 
	AND IM_CTD_ON BETWEEN @openingStockDateFrom AND @openingStockDateTo 
	GROUP BY ITM_CODE,C_ID,PLANT_ID,LANG_ID,WH_ID,LANG_ID) X ON 
	X.C_ID = TH.C_ID AND X.PLANT_ID = TH.PLANT_ID AND X.LANG_ID = TH.LANG_ID AND X.ITM_CODE=TH.ITM_CODE

	-- PAL Temp Table to THR (closingStock)
	UPDATE TH SET TH.PA_CS_QTY = X.VALUE FROM #THR TH INNER JOIN
	(SELECT SUM(PA_CNF_QTY) VALUE,ITM_CODE, C_ID, PLANT_ID, WH_ID, LANG_ID FROM #PAL 
	WHERE 
	--ITM_CODE IN (SELECT ITM_CODE FROM #ITC) AND 
	C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND 
	STATUS_ID IN (20) AND
	WH_ID=@warehouseId 
	AND PA_CTD_ON BETWEEN @closingStockDateFrom AND @closingStockDateTo 
	GROUP BY ITM_CODE,C_ID,PLANT_ID,LANG_ID,WH_ID,LANG_ID) X ON 
	X.C_ID = TH.C_ID AND X.PLANT_ID = TH.PLANT_ID AND X.LANG_ID = TH.LANG_ID AND X.ITM_CODE=TH.ITM_CODE

	-- PUL Temp Table to THR (closingStock)
	UPDATE TH SET TH.PI_CS_QTY = X.VALUE FROM #THR TH INNER JOIN
	(SELECT SUM(PICK_CNF_QTY) VALUE,ITM_CODE, C_ID, PLANT_ID, WH_ID, LANG_ID FROM #PUL 
	WHERE 
	--ITM_CODE IN (SELECT ITM_CODE FROM #ITC) AND 
	C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND 
	STATUS_ID IN (50,59) AND
	WH_ID=@warehouseId 
	AND PICK_CTD_ON BETWEEN @closingStockDateFrom AND @closingStockDateTo 
	GROUP BY ITM_CODE,C_ID,PLANT_ID,LANG_ID,WH_ID,LANG_ID) X ON 
	X.C_ID = TH.C_ID AND X.PLANT_ID = TH.PLANT_ID AND X.LANG_ID = TH.LANG_ID AND X.ITM_CODE=TH.ITM_CODE

	-- IVM Temp Table to THR (closingStock)
	UPDATE TH SET TH.IV_CS_QTY = X.VALUE FROM #THR TH INNER JOIN
	(SELECT SUM(MVT_QTY) VALUE,ITM_CODE, C_ID, PLANT_ID, WH_ID, LANG_ID FROM #IVM 
	WHERE 
	--ITM_CODE IN (SELECT ITM_CODE FROM #ITC) AND 
	C_ID = '1000' AND LANG_ID = 'EN' AND PLANT_ID = '1001' AND 
	MVT_TYP_ID = 4 AND SUB_MVT_TYP_ID = 1 AND
	WH_ID=@warehouseId 
	AND IM_CTD_ON BETWEEN @closingStockDateFrom AND @closingStockDateTo 
	GROUP BY ITM_CODE,C_ID,PLANT_ID,LANG_ID,WH_ID,LANG_ID) X ON 
	X.C_ID = TH.C_ID AND X.PLANT_ID = TH.PLANT_ID AND X.LANG_ID = TH.LANG_ID AND X.ITM_CODE=TH.ITM_CODE
	
	TRUNCATE TABLE tbltransactionhistoryresults
	
	INSERT INTO tbltransactionhistoryresults(warehouse_id,opening_stock,inbound_qty,outbound_qty,stock_adjustment_qty,system_inventory,item_code,description,closing_stock)
	(
	SELECT *,
	(openingStock+inboundQty+stockAdjustmentQty-outboundQty) closingStock
	FROM
	(SELECT
	wh_id warehouseId,
	((COALESCE(IS_OS_QTY,0)+COALESCE(PA_OS_QTY,0)+COALESCE(IV_OS_QTY,0))-COALESCE(PI_OS_QTY,0)) openingStock,
	COALESCE(PA_CS_QTY,0) inboundQty,
	COALESCE(PI_CS_QTY,0) outboundQty,
	COALESCE(IV_CS_QTY,0) stockAdjustmentQty,
	COALESCE(IV_QTY,0) systemInventory,
	ITM_CODE itemCode,
	TEXT description
	FROM #THR) X)
		
END

GO